# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CabbageCat's Blogs

social-network-links:
  email: "zh13352256336@hotmail.com"
  github: szhaovas
  youtube: channel/UC9Sq0RWksSKqsOMgXGGRfkQ

# Build settings
remote_theme: szhaovas/beautiful-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap

# Theme
avatar: "/assets/images/avatar.png"
round-avatar: true
navbar-col: "#8C7109"
# page-img: "/assets/images/scene_alpha.png"
footer-col: "#8C7109"
footer-link-col: "#704917"
footer-hover-col: "#A67432"
hover-col: "#707070"

site-css:
  - "/assets/css/custom-styles.css"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

google_analytics: "UA-240211210-1"
gtag: "UA-240211210-1"
